services:
  - type: web
    name: sleepai-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health